# Generated by Django 5.2.8 on 2025-11-22 14:15

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_text', models.TextField()),
                ('content_html', models.TextField(blank=True, null=True)),
                ('images', models.JSONField(default=list)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('link_url', models.URLField(blank=True, null=True)),
                ('link_preview', models.JSONField(blank=True, null=True)),
                ('scheduled_time', models.DateTimeField()),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('is_optimal_time', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('published', 'Published'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('platform_post_id', models.CharField(blank=True, max_length=255, null=True)),
                ('platform_post_url', models.URLField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('engagement_data', models.JSONField(blank=True, null=True)),
                ('last_analytics_fetch', models.DateTimeField(blank=True, null=True)),
                ('generated_content_id', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='PublishedPostAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('shares_count', models.IntegerField(default=0)),
                ('retweets_count', models.IntegerField(default=0)),
                ('saves_count', models.IntegerField(default=0)),
                ('impressions', models.IntegerField(default=0)),
                ('reach', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('engagement_rate', models.FloatField(default=0.0)),
                ('ctr', models.FloatField(default=0.0)),
                ('audience_data', models.JSONField(blank=True, null=True)),
                ('first_fetch_at', models.DateTimeField(auto_now_add=True)),
                ('last_fetch_at', models.DateTimeField(auto_now=True)),
                ('scheduled_post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='social.scheduledpost')),
            ],
            options={
                'verbose_name_plural': 'Published post analytics',
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('twitter', 'Twitter/X'), ('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=50)),
                ('account_name', models.CharField(max_length=255)),
                ('account_id', models.CharField(max_length=255)),
                ('account_handle', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_image_url', models.URLField(blank=True, null=True)),
                ('access_token', encrypted_model_fields.fields.EncryptedTextField()),
                ('refresh_token', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('account_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='social_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_posts', to='social.socialaccount'),
        ),
        migrations.CreateModel(
            name='PostingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('hour_utc', models.IntegerField()),
                ('minute', models.IntegerField(default=0)),
                ('score', models.FloatField()),
                ('reason', models.TextField()),
                ('based_on_data', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score'],
                'indexes': [models.Index(fields=['user', 'platform', '-score'], name='social_post_user_id_bcc3f5_idx')],
                'unique_together': {('user', 'platform', 'day_of_week', 'hour_utc', 'minute')},
            },
        ),
        migrations.AddIndex(
            model_name='socialaccount',
            index=models.Index(fields=['user', 'platform'], name='social_soci_user_id_190af1_idx'),
        ),
        migrations.AddIndex(
            model_name='socialaccount',
            index=models.Index(fields=['is_active'], name='social_soci_is_acti_979b44_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together={('user', 'platform', 'account_id')},
        ),
        migrations.AddIndex(
            model_name='scheduledpost',
            index=models.Index(fields=['user', 'status'], name='social_sche_user_id_d24588_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledpost',
            index=models.Index(fields=['scheduled_time', 'status'], name='social_sche_schedul_a04318_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledpost',
            index=models.Index(fields=['social_account', 'status'], name='social_sche_social__ab5bf8_idx'),
        ),
    ]
