# Generated by Django 5.2.8 on 2025-11-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='brand_voice',
            field=models.TextField(blank=True, help_text='The active system instruction for AI generation.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='voice_fingerprint',
            field=models.JSONField(blank=True, default=dict, help_text='Full analysis data including metrics and name.'),
        ),
    ]
