from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db import transaction

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    
    # Brand Settings
    company_name = models.CharField(max_length=100, blank=True)
    target_audience = models.TextField(blank=True, help_text="Who are you writing for?")
    
    # This field now stores the specific "System Instruction" generated by the AI
    brand_voice = models.TextField(
        blank=True, 
        help_text="The active system instruction for AI generation."
    )
    
    # The "DNA" Data: Stores the radar chart metrics, keywords, and voice name
    voice_fingerprint = models.JSONField(
        default=dict, 
        blank=True, 
        help_text="Full analysis data including metrics and name."
    )
    
    def __str__(self):
        return f"{self.user.username}'s Profile"

# Auto-create profile when User is created
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        try:
            # Use atomic transaction to ensure safety
            with transaction.atomic():
                UserProfile.objects.get_or_create(user=instance)
        except Exception as e:
            # Gracefully fail if table doesn't exist (e.g. during initial migration)
            import logging
            logging.warning(f"Could not create UserProfile: {e}")

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    if not kwargs.get('created', False):  # Only save on update, not on creation
        try:
            if hasattr(instance, 'profile'):
                instance.profile.save()
        except (UserProfile.DoesNotExist, AttributeError, Exception) as e:
            # If profile doesn't exist yet or any other error, ignore
            import logging
            logging.warning(f"Could not save UserProfile: {e}")