# Generated by Django 5.2.8 on 2025-11-19 18:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('remove_bg', 'Remove Background'), ('upscale', 'Upscale Image'), ('restore_face', 'Restore Face'), ('video_scenes', 'Detect Video Scenes'), ('video_transcribe', 'Transcribe Video')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('input_file', models.FileField(upload_to='media_jobs/input/%Y/%m/%d/')),
                ('output_file', models.FileField(blank=True, null=True, upload_to='media_jobs/output/%Y/%m/%d/')),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
