# Generated by Django 5.2.8 on 2025-11-23 12:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0001_initial'),
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediajob',
            name='input_file',
            field=models.FileField(blank=True, null=True, upload_to='media_jobs/input/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='mediajob',
            name='job_type',
            field=models.CharField(choices=[('remove_bg', 'Remove Background'), ('upscale', 'Upscale Image'), ('restore_face', 'Restore Face'), ('video_scenes', 'Detect Video Scenes'), ('video_transcribe', 'Transcribe Video'), ('ai_image_generation', 'AI Image Generation')], max_length=50),
        ),
        migrations.CreateModel(
            name='ProcessedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('collage', 'Collage'), ('framed', 'Framed Individual'), ('social_ready', 'Social Media Ready')], max_length=20)),
                ('image_file', models.ImageField(upload_to='processed_images/%Y/%m/%d/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('width', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('file_size', models.IntegerField(null=True)),
                ('processing_params', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processed_images', to='ingest.uploadedfile')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processed_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
